# -*- coding: utf-8 -*-
"""
Created on Tue Jul 14 15:00:35 2020

@author: CheikhMoctar
"""


us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
     'Washington DC': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Minnessota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
    ####################
    'Alberta': 'AB' ,
    'British Columbia' :'BC',
    'Manitoba': 'MB',
    'New Brunswick':'NB' ,
    'Newfoundland and Labrador':'NL' ,
    'Northwest Territories': 'NT' ,
    'Nova Scotia':'NS',
    'Nunavut':'NU' ,
    'Ontario':'ON' ,
    'Prince Edward Island':'PE',
    'Quebec':'QC' ,
    'Saskatchewan':'SK',
    'Yukon':'YT' 
}

st_dict = {'st':'street', 'pkwy':'parkway', 'ave':'avenue', 'dr': 'drive', 'rd':'road', 'blvd':'boulevard', 'ln':'lane', 'hwy':'highway'}
dir_dict = {'e':'east', 'w':'west', 's':'south', 'n': 'north', 'ne':'north east', 'nw':'north west', 'se':'south east', 'sw':'south west'}